version: "3"

services:
  jp_app:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=jp_app
      - FLASK_DEBUG=true
    command: flask run --host=0.0.0.0
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    ports:
      - "3000:90"
    depends_on:
      - jp_app
    environment:
      - FLASK_APP=JP_APP